language: ruby
rvm:
  - 2.0.0
  - 2.1.4
  - 2.2.0
  - 2.2.2
  - jruby
  - rbx-2
  - 1.9.3
  - ruby-head
  - jruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  # Only use 1 job until Travis fixes the rbx --jobs issue.
  - if [ "$TRAVIS_RUBY_VERSION" == "rbx-2" ] ; then export BUNDLE_JOBS=1 ; else export BUNDLE_JOBS=4; fi

sudo: false

notifications:
  irc: "irc.freenode.org#emotive"
